# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d9521a00304c11826b58cf48feddf0401cc04772358d1834b9d76b3e761e6bba91e8cd06b831109e15eb8fabe4cd5cd1d707f47c1055b798dc3bc3386ff68fd7

test:
  secret_key_base: 65a32e63a942e83832a9f925a1b20749e678d5c7d3f258e3471fb0387a18559d7c154930b1e7e41452e228b4428c3035a4efb957bdc900dc8c627299e6ef3a0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
